### PR TITLE
As/animation fix

### PR DESCRIPTION
**Pull request by anbitasiregar**

### CODE REVIEW

**Comment by luquantan** [comment]
The main spinner animation(the big searching for networks spinner) does not continue after a presented view controller is dismissed.
Repro steps:
1) Start app. Disable test routers, so the big spinner stays there.
2) Background the app by press home button.
3) Tap on app icon to foreground the app.
4) Open the app log.
5) Wait a second, then press "Ok" to dismiss the app log
6) The spinner doesn't spin anymore

All these steps can be repeated from the border router screen where the small spinner popup is present. Backgrounding the app followed by presenting and then dismissing a view controller will cause the spinner to stop spinning.

**Comment by anbitasiregar** [comment]
Note: I think the popup spinner should be refactored and just be an instance of TGSpinnerView because they seem to be doing the same thing. Thoughts @luquantan @ButkiewiczP ?

**Comment by luquantan** [comment]
Not really. Because `TGNetworkSeachingPopup` also contains the label and background colors that are different than `TGSpinnerView`. Although, the notification and animation code within `TGNetworkSearcjingPopup.m` should be removed since all that functionality should be contained within `TGSpinnerView`

**Comment by anbitasiregar** [comment]
We actually still need all the notification and animation code in TGNetworkSearchingPopup.m. Because it's not a subclass of TGSpinnerView, [self startAnimating] won't register in TGNetworkSearchingPopup

**Pull request closed without merging**
